version: '3.9'

services:
  db:
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD:-build}"
      MARIADB_DATABASE: "${MARIADB_DATABASE:-build}"
      MARIADB_USER: "${MARIADB_USER:-build}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD:-build}"

  wordpress:
    environment:
      WORDPRESS_DB_USER: "${MARIADB_USER:-build}"
      WORDPRESS_DB_PASSWORD: "${MARIADB_PASSWORD:-build}"
      WORDPRESS_DB_NAME: "${MARIADB_DATABASE:-build}"
      WORDPRESS_TABLE_PREFIX: "${WORDPRESS_TABLE_PREFIX:-build}"
      WORDPRESS_CONFIG_EXTRA: "define('API_SECRET', '${WORDPRESS_API_SECRET:-build}');"

  wp-cli:
    environment: 
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST:-db}"
      WORDPRESS_DB_USER: "${MARIADB_USER:-build}"
      WORDPRESS_DB_PASSWORD: "${MARIADB_PASSWORD:-build}"
      WORDPRESS_DB_NAME: "${MARIADB_DATABASE:-build}"
      WORDPRESS_TABLE_PREFIX: "${WORDPRESS_TABLE_PREFIX:-build}"
      WORDPRESS_CONFIG_EXTRA: "define('API_SECRET', '${WORDPRESS_API_SECRET:-build}');"
      WP_URL: "${WP_URL:-build}"
      WP_TITLE: "${WP_TITLE:-build}"
      WP_ADMIN_USER: "${WP_ADMIN_USER:-build}"
      WP_ADMIN_PASSWORD: "${WP_ADMIN_PASSWORD:-build}"
      WP_ADMIN_MAIL: "${WP_ADMIN_MAIL:-build@example.com}"

  www:
    environment:
      WORDPRESS_API_SECRET: "${WORDPRESS_API_SECRET:-build}"
