version: '3.9'

services:
  nginx:
    build: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443

  db:
    image: mariadb:10.7
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"

  api:
    build: packages/api
    container_name: api
    restart: unless-stopped

  wordpress:
    depends_on:
      - db
    build: wordpress
    container_name: wordpress
    # volumes:
    #   - wordpress_data:/var/www/html
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_TABLE_PREFIX: "${WORDPRESS_TABLE_PREFIX}"

  www:
    build: packages/www
    container_name: www
    restart: unless-stopped

volumes:
  db_data: {}
  wordpress_data: {}
