import type { NextPage } from "next";
import Head from "next/head";

import PostService, { PostFindAllResponse } from "../services/wordpress/post.service";

import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";

interface HomeProps {
  posts: PostFindAllResponse;
}

const Home: NextPage<HomeProps> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Sebastian Gonzalez Quintero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack>
        <Typography>Hello world</Typography>
      </Stack>
    </>
  );
};

export default Home;

export async function getStaticProps() {
  const posts = await PostService.findAll();
  return {
    props: { posts },
  };
}
