import type { NextPage } from "next";
import Head from "next/head";

import Stack from "@mui/material/Stack";
import { Typography } from "@mui/material";

const Post: NextPage = ({  }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack>
        <Typography>
          Hello world
        </Typography>
      </Stack>
    </>
  );
};

export default Post;
