name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  docker:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build the Docker images
      run: docker-compose -f docker-compose.yml -f docker-compose.build.yml build
      
    - name: Run the Docker containers
      run: docker-compose -f docker-compose.yml -f docker-compose.build.yml up -d
    
    - name: Stop the Docker containers
      if: always()
      run: docker-compose down
